#!/bin/bash

  OPATH=$PATH
  PATH=.:./Linux:$OPATH

  clear && rexx cmpsctst.rexx  ./FILES/SMALL/EBCDIC  ./DICTS  ./WORK  -a    -n      -r 4 -z  >  ./WORK/cmpsctst-ser-a.log
  clear && rexx cmpsctst.rexx  ./FILES/LARGE/EBCDIC  ./DICTS  ./WORK  -a    -n      -r 4 -z  >  ./WORK/cmpsctst-ler-a.log
  clear && rexx cmpsctst.rexx  ./FILES/SMALL/ASCII   ./DICTS  ./WORK  -a -t -n      -r 4 -z  >  ./WORK/cmpsctst-sar-a.log
  clear && rexx cmpsctst.rexx  ./FILES/LARGE/ASCII   ./DICTS  ./WORK  -a -t -n      -r 4 -z  >  ./WORK/cmpsctst-lar-a.log
