#!/bin/bash

  OPATH=$PATH
  PATH=.:./Linux:$OPATH

  clear && rexx cmpsctst.rexx  ./FILES/SMALL/EBCDIC  ./DICTS  ./WORK  -a    -b1 -o1 -r 0 -z  >  ./WORK/cmpsctst-sen-a.log
  clear && rexx cmpsctst.rexx  ./FILES/LARGE/EBCDIC  ./DICTS  ./WORK  -a    -b1 -o1 -r 0 -z  >  ./WORK/cmpsctst-len-a.log
  clear && rexx cmpsctst.rexx  ./FILES/SMALL/ASCII   ./DICTS  ./WORK  -a -t -b1 -o1 -r 0 -z  >  ./WORK/cmpsctst-san-a.log
  clear && rexx cmpsctst.rexx  ./FILES/LARGE/ASCII   ./DICTS  ./WORK  -a -t -b1 -o1 -r 0 -z  >  ./WORK/cmpsctst-lan-a.log
