#!/bin/bash

  OPATH=$PATH
  PATH=.:./Linux:$OPATH

  clear && rexx cmpsctst.rexx  ./FILES/SMALL/EBCDIC  ./DICTS  ./WORK        -n      -r 4 -z  >  ./WORK/cmpsctst-ser.log
  clear && rexx cmpsctst.rexx  ./FILES/LARGE/EBCDIC  ./DICTS  ./WORK        -n      -r 4 -z  >  ./WORK/cmpsctst-ler.log
  clear && rexx cmpsctst.rexx  ./FILES/SMALL/ASCII   ./DICTS  ./WORK     -t -n      -r 4 -z  >  ./WORK/cmpsctst-sar.log
  clear && rexx cmpsctst.rexx  ./FILES/LARGE/ASCII   ./DICTS  ./WORK     -t -n      -r 4 -z  >  ./WORK/cmpsctst-lar.log
