#!/bin/bash

  OPATH=$PATH
  PATH=.:./Linux:$OPATH

  clear && cmpsctst.rexx  ./FILES/SMALL/EBCDIC  ./DICTS  ./WORK        -b1 -o1 -r 0 -z  >  ./WORK/cmpsctst-sen.log
  clear && cmpsctst.rexx  ./FILES/LARGE/EBCDIC  ./DICTS  ./WORK        -b1 -o1 -r 0 -z  >  ./WORK/cmpsctst-len.log
  clear && cmpsctst.rexx  ./FILES/SMALL/ASCII   ./DICTS  ./WORK     -t -b1 -o1 -r 0 -z  >  ./WORK/cmpsctst-san.log
  clear && cmpsctst.rexx  ./FILES/LARGE/ASCII   ./DICTS  ./WORK     -t -b1 -o1 -r 0 -z  >  ./WORK/cmpsctst-lan.log
